### ISSUE TITLE
Unresolved reference of String.lowercase() in Kotlin code

### ISSUE THREAD

**Issue by shinji-newrelic** [newrelic/java-log-extensions#63] opened 2022-06-24 00:49 UTC
The build was failed with "Unresolved reference" if String.lowercase() is used in the Kotlin code. for example;

`println("Hello World!".lowercase())`

This error appears on the version 2.4.0 and 2.5.0. No build error with version 2.3.2.

(migrate to Jira)

**Comment by niclange** [comment] 2022-08-25 07:48
We encounter the same issue with Kotlin.

**Comment by kford-newrelic** [comment] 2022-09-12 14:11
Confirmed that the issue is that it's the application build that fails when using `java-log-extensions`

Attached sample app is said to reproduce the problem.

[test-kotlin.zip](https://github.com/newrelic/java-log-extensions/files/9548776/test-kotlin.zip)

**Comment by meiao** [comment] 2022-09-13 17:18
This is likely a duplicate of #56

**Comment by jasonjkeller** [comment] 2022-09-13 17:28
Yep, agree with @meiao . Likely a conflict with Kotlin dependencies used by OkHttp that are pulled in via the TelemetrySDK dependency.

**Closed** 2022-09-23 11:34 UTC
Labels: Q3 SC
